name: nomads_wallet
description: Nomads.one Digital Wallet — QR Pay, Send, Exchange
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.3.0
  mobile_scanner: ^6.0.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.0
  flutterwave_standard: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
